# Generated by Django 4.2 on 2024-12-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CVE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('base_score_v2', models.FloatField(blank=True, null=True)),
                ('base_score_v3', models.FloatField(blank=True, null=True)),
                ('last_modified', models.DateTimeField()),
                ('published_date', models.DateTimeField()),
            ],
        ),
    ]
